spring:
  application:
    name: biblioteca
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

app:
  jwt:
    secret: ${JWT_SECRET:FEÇD58D4531F5827E82374S5WD51Ç72D}
    expiration-seconds: 3600
